# Part of `travis-lazarus` (https://github.com/nielsAD/travis-lazarus)
# License: MIT

language: generic
sudo: required
dist: trusty


os:
  - linux

env:
  global:
    - DISPLAY=:99.0
  matrix:
    - LAZ_VER=1.8.2 LAZ_ENV=linux LAZ_OPT="--os=linux --cpu=x86_64"

before_install:
  # Start virtual display server
  - Xvfb $DISPLAY &
  - chmod +x ./ci/travis.install.py
  - chmod +x ./ci/travis.compile.py

install:
  - ./ci/travis.install.py

script:
  - lazbuild pck/paxjson_package.lpk
  - lazbuild pck/tests.lpr
  - lazbuild pck/demos/jsonDemo.lpr
  - ls -1 bin/*
  - ./bin/test/x86_64/tests -a --format=plain

notifications:
  email:
    on_success: false
    on_failure: change
